### ISSUE TITLE
Run phproject in subdirectory

### ISSUE THREAD

**Issue by svenbw** [Alanaktion/phproject#111]
If you want to run the code in a subdirectory and not in the root of webserver the configuration of the framework needs to be changed; the *ROOT* variable should be assigned to the directory where *index.php* is located.
This can be done by adding the following line to the mset array (in *index.php*).
`"ROOT" => realpath(dirname(__FILE__)).DIRECTORY_SEPARATOR`

Maybe this should be added to the documentation or in the *index.php* file by default.

**Comment by Alanaktion** [comment]
The site works for me in a subdirectory with no changes to code or configuration, at least on Apache. What web server are you using?

**Comment by svenbw** [comment]
I tweaked .htaccess a little more, but this finally resulted in the error below:
`[phproject/lib/base.php:2015] Base->error(500,'is_file(): open_basedir restriction in effect. File(app/plugin/README.md/base.php) is not within the allowed path(s): (some_paths_on_the_server)')
[phproject/index.php:89] is_file('app/plugin/README.md/base.php')`

The plugin scan code looks for entries under the app/plugin directory, README.MD is one of them. This causes in an error because it's a file.

modifying line 89 in 
`if($pluginName != "." && $pluginName != ".." && is_dir("app/plugin/$pluginName") && is_file("app/plugin/$pluginName/base.php") && is_dir("app/plugin/$pluginName/dict/")) {`

and line 97 in
`if($pluginName != "." && $pluginName != ".." && is_dir("app/plugin/$pluginName") && is_file("app/plugin/$pluginName/base.php")) {`

solves the problem because it wil only check for the plugins *base.php* if the entry is a directory.

**Comment by Alanaktion** [comment]
I believe I've fixed this issue in commit 3495454.
