### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#115]
I'd reaaaaally like to implement this Markdown editor... it's beautiful and perfect and I love it sooo much, seriously.
https://github.com/NextStepWebs/simplemde-markdown-editor/

Along with this, I'd like to make sure the markdown parser we're using supports the same table formatting syntax.

And maybe deprecate Textile and include a conversion thingy... although that may be a bit much.

**Comment by ikkez** [comment]
That markdown editor looks great. I guess it's worth a try, even if it maybe isn't that battle-tested yet. Go for it! :)

**Comment by KindlyFire** [comment]
Seems nice !

**Comment by Rayne** [comment]
I love the combination of WYSIWYG and the source code in one view.

Isn't it lacking support for tables?

**Comment by KindlyFire** [comment]
It supports Markdown Tables. I just implemented it in my website (https://www.youtube.com/watch?v=f3vl7zwKO7w) on a private paste service I made.

**Comment by Alanaktion** [comment]
I've implemented the editor in the `mde` branch. I've also replaced all of the Glyphicons icons with Font Awsome as well, since it's a requirement for the markdown editor.
