### ISSUE TITLE
Login URL was not found

### ISSUE THREAD

**Issue by skapykat** [Alanaktion/phproject#117]
I am trying to install phptoject and keep getting "The requested URL /login was not found on this server." after I run install.php. I get the same error on Ubuntu 14 and CentOS 6/7. i have installed from zip and cloned the repo, I have relaxed the directory perms(777) and turned off selinux all with the same ending. Is there a step missing in the install instructions or should the owner be something other than root? Thanks.

**Comment by Alanaktion** [comment]
If you are running Apache, you need to make sure you have `mod_rewrite` enabled, and you've set `AllowOverride All` for the directory in your Apache configuration. If you're running some other web server, make sure you've set up URL rewrites. Nginx should be configured as shown in the `nginx-example.conf` file, if that's what you're using. I haven't tried the project on any other servers.

**Comment by skapykat** [comment]
mod_rewrite was the issue. I missed that in the requirements. Thanks for the help.
