### ISSUE TITLE
Admin page section links do not work

### ISSUE THREAD

**Issue by skapykat** [Alanaktion/phproject#123]
When I am on the admin page and tray to click on a subsection (i.e. email) the url changes, but the page does not. I cannot edit any of the advanced configuration settings. I should also note that the save button also doesn't appear.

**Comment by Alanaktion** [comment]
I'm unable to reproduce this issue on any of my test sites. If you set the `DEBUG` mode to `3` and view the page source, you may have a relevant error message at the bottom of the code that could help in further diagnosing this.
Also, there is no save button on the Configuration forms, each field is saved automatically when changed.
