### ISSUE TITLE
Useful features

### ISSUE THREAD

**Issue by andydavey82** [Alanaktion/phproject#130]
Hi i am a big fan of this software its great and simple to use, but i feel the following could be improved:
When adding a task or subproject, it would be better to use a select box for parentID with title instead of just adding an id number, or even display a scroll-able list with title and ID, to make it easier to choose.

**Comment by Alanaktion** [comment]
You can already use the typeahead search that's in the parent ID box now, does it not work in some places? It should let you type a project or task name and click it to enter the item's ID.
