### ISSUE TITLE
Home page, displaying projects, sub-projects and tasks

### ISSUE THREAD

**Issue by andydavey82** [Alanaktion/phproject#131]
A useful feature would be to also have the last 10 or so comments made, placed here too.

**Comment by Alanaktion** [comment]
I would definitely like to do this, I think I'm going to expand it a bit and make the home page customizable, with several new boxes you could add and move around on it.

**Comment by Alanaktion** [comment]
I've added two comment box choices to the new Dashboard widgets, you can add items now to list recent comments by others on your issues, or recent comments you've made on other issues.
