### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by mardon** [Alanaktion/phproject#132]
I want to translate to czech language, but how I acn add translation i added my file cs.ini to dict foleder, but how i set this language to use in application?

**Comment by Alanaktion** [comment]
You can change the `language` column to `cs` in the `user` database table.
Or, edit the `app/controller/user.php` file, adding `"cs" => \ISO::LC_cs` under the Nederlands line. This will let you select "Czech" under the language setting in your account.

Also, the Czech language has been added to the project on CrowdIn, if you want to translate it there: https://crowdin.com/project/phproject/cs

**Comment by mardon** [comment]
i have updated czech translation in my local installation. want to sent him?

**Comment by Alanaktion** [comment]
Yes, that would be great. You can upload it here, submit a pull request, or [add it on CrowdIn](https://crowdin.com/project/phproject/cs).
