### ISSUE TITLE
Add dictionary support to Dashboard Widgets modal

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#142]

**Comment by BerChill** [comment]
I think this was solved with commit 0f4af9549f1d763dc34102f758ce8de6a7081673 but please check again if we are on the same page with that.

**Comment by Alanaktion** [comment]
It looks like that commit and 4d134a61a03d1a4063b1626b7b73f2f1e4ac714d added it, yep. Thanks! I'l close this.
