### ISSUE TITLE
Notification Mail Content is broken

### ISSUE THREAD

**Issue by ikkez** [Alanaktion/phproject#158]
It seems like all mails are empty at the moment.
It would be great when the notification mails contain some content. Really useful at first would be:

*  Task description of the new task in the "new task created" notification mails
*  The comment text in "new comment on .." notification mails

**Comment by ikkez** [comment]
Oh wait, I can see in the raw mail message now that there is the email body. Unfortunately doesn't show up in google mail, so I thought it's empty. How do you send mails? Maybe there is a bug somewhere on transcoding the html message body.

**Comment by Alanaktion** [comment]
I've never had trouble seeing notification content in Gmail, OS X Mail, Thunderbird or similar. I've merged your pull request.

**Comment by ikkez** [comment]
works great now. thanks.
