### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by w3bariak** [Alanaktion/phproject#160]
Hello, I have run into a problem with installation. After successful installation, when I navigate to the site url (domain.com) I got a 500 error. Could you help me ?

[lib/base.php:2015] Base->error(500,'PDO::__construct() expects parameter 3 to be string, array given')

**Comment by Alanaktion** [comment]
It sounds like there's a problem with your database connection configuration. I haven't been able to reproduce this issue on a new installation, but there are some things you can try. Make sure your `config.ini` file looks similar to this:
```ini
[globals]
db.host=localhost
db.user=root
db.pass=password
db.name=phproject
```
If your file has additional lines, that's fine, but make sure the database connection details are accurate and structured like they're shown above. If that's not the issue, try adding `DEBUG = 3` to your `config.ini` file to get a more detailed error message, I may be able to help more if I can see better what's going on.

**Comment by steinhmor** [comment]
i also got a 500 error a few days ago and thought, it just might be my server...
after pressing F5 my site worked fine
i'll share details with you if it happens again.

**Comment by w3bariak** [comment]
I am still seeing the error, can't solve that. Just that error occurs, but on PHP 5.4. On a newer versions of PHP it doesn't happen, but after seting debug=3, another error comes - after adding widget on homepage (PHP 5.6.15)

**Comment by Alanaktion** [comment]
The widget adding issue should be resolved. I still haven't been able to reproduce that initial 500 error, though I am running a more recent PHP. I'll try installing 5.4 and see what I can find.

**Comment by Alanaktion** [comment]
I can't find any errors on a new install on PHP 5.3 or 5.4. The issue may have been resolved already, let me know if you have any errors again.
