### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by w3bariak** [Alanaktion/phproject#164]
After fresh installation of phproject, this error popups when I try to add widget to dashboard page.

```
PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND user_id != 1 ORDER BY `created_date` DESC LIMIT 15' at line 1
```
Installed at localhost, PHP 5.6.15, MariaDB 10.1.9.

**Comment by w3bariak** [comment]
Could someone look at that error ?

**Comment by Alanaktion** [comment]
I think I've got this figured out. If you add one of the comment widgets, but have no open issues to display comments for, it fails. I'll get a fix for it released in just a minute.
