### ISSUE TITLE
Time track

### ISSUE THREAD

**Issue by tes5884** [Alanaktion/phproject#167]
Not sure if this is the right forum.

Is there currently a way to track time spent on a specific task? If not, is that something you'd consider adding?

Thanks - really liking this project so far!

**Comment by Alanaktion** [comment]
There is, though it's not yet very clear how to use it. There is a "total hours spent" field on each task that can be updated with the number of hours spent, and the user page includes a graph of the total hours spent each day for that user. You may also want to look at the [teamdaily](https://github.com/phproject-plugins/teamdaily) plugin, which adds a department overview including total hours spent by date.
