### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by w3bariak** [Alanaktion/phproject#178]
After fresh installation of Phproject, latest commit #9734dcb there is an error.

`PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8' at line 7`

**Comment by Alanaktion** [comment]
I believe I've fixed this issue. Thanks for reporting it!
