### ISSUE TITLE
Taskboard gone?

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#189]
Hi Alan,

is the taskboard advertised on the project page implemented? I can't find/access it through the interface of my installation or the demo application.

Greatly appreciate your work!

**Comment by Alanaktion** [comment]
The taskboard is still available. Taskboards are per-sprint, accessed from the Sprints page, then clicking the backlog button on a specific sprint. If there's currently an active sprint, a taskboard button will also show on the dashboard page.
The only sprints on the demo site are in the past, so you can access them on the [Previous Sprints page](http://demo.phproject.org/backlog/old).
