### ISSUE TITLE
group name text field always shows "admin" when editing the group

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#192]
BUG-COSMETICAL

OBSERVED BEHAVIOR:
When editing groups the group name field always shows "admin" (eg. either username of administrator or first user in user table which would be true for both in my instance). This bug has no functional implications since "admin" is not saved as the new group name unless the user enters the text field.
![editing-groups](https://cloud.githubusercontent.com/assets/18327444/14438190/13354c72-0025-11e6-9fc7-0bc375a20d2b.JPG)

EXPECTED BEHAVIOR:
When editing a group the group name text field shows the current name of the group

**Comment by Alanaktion** [comment]
![phproject-group-test](https://cloud.githubusercontent.com/assets/236490/14438656/646f0ace-ffe4-11e5-930e-efc5abe19584.png)
I'm unable to reproduce this issue on the demo site or any of my local copies, but I'll look into it some more to see if there's an obvious potential cause.

**Comment by BerChill** [comment]
I am sorry. Looking into it a bit further I found out that my login manager add-on for firefox (keeFox) autofills the text field with the user name used for the login. It works fine when the add-on is disabled.
