### ISSUE TITLE
Allow a user to change the group tasks color

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#193]
ENHANCEMENT

OBSERVED BEHAVIOR
Once a group has been created the group tasks color cannot be changed through the group administration interface.

EXPECTED BEHAVIOR
The user can change the color of group tasks through the "edit group screen" analog to the color selector in the "edit user screen"

**Comment by Alanaktion** [comment]
This has been added.

**Comment by BerChill** [comment]
Thank you, you're awesome! I'm very close to learning PHP so I can contribute to this project :smile:
