### ISSUE TITLE
Admin Panel still shows Updates after updating

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#195]
BUG-MINOR-UI

OBSERVED BEHAVIOR
After updating the server via FTP upload of the latest .zip from GitHub, the Admin Panel still shows that there are updates available. (This hasn't been the case a couple of weeks ago but I cannot say if it is related to the server config or some caching issue) Clearing the browser cache doesn't solve the issue.
![updates](https://cloud.githubusercontent.com/assets/18327444/14761622/dc3a1978-0966-11e6-9dc4-2700606fac0e.JPG)

EXPECTED BEHAVIOR
The Admin Panel only shows the number of updates that are available with regards to the version installed. Also, it would be nice if one could click the number which would open the github page in a new tab.

**Comment by Alanaktion** [comment]
That field doesn't show the available updates for the code, it shows the number of updates made to issues on your site. It might be better to show a different metric of just remove that section.

**Comment by BerChill** [comment]
I see. Then it would be great if the field showed the behavior described above. If you like the idea, I could change the issue so that it describes this use case. Otherwise, go ahead and close the issue.

**Comment by Alanaktion** [comment]
I'll add a new issue as a feature request for that. I'd like to keep this one open as a reminder to fix the ambiguity of the existing field.
