### ISSUE TITLE
Allow for private projects

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#197]
ENHANCEMENT-MAJOR-RIGHTSMANAGEMENT

OBSERVED BEHAVIOR
Currently, all projects can be viewed by all users.

EXPECTED BEHAVIOR
It would be great if users with the right to create projects could declare them as private so that the project and its tasks are only visible to users assigned to it.

**Comment by Alanaktion** [comment]
This is already open as #45 Private issues
