### ISSUE TITLE
Research alternatives to using MySQL views

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#228]
Something like [ikkez/f3-cortex](https://github.com/ikkez/f3-cortex) could be just what we need. I'm not planning on leaving F3 any time soon, so this may be a good starting point.

**Comment by Rayne** [comment]
Any news or new ideas for replacing SQL views?

**Comment by Alanaktion** [comment]
@Rayne I'll most likely be implementing [ikkez/f3-cortex](https://github.com/ikkez/f3-cortex). If that doesn't work out, I'm planning on trying to build my own layer on top of the F3 ORM that works similar to Cortex but more tuned to the needs of the project.
