### ISSUE TITLE
Markdown Editor Flashing Delay

### ISSUE THREAD

**Issue by volomike** [Alanaktion/phproject#231]
I noticed when creating a new project or task, where the form opens and it shows the toolbar, it's flashing, then disappearing, then showing up again. Can you figure out what's causing that or hide the form a second until that's straightened out, then show the form?

**Comment by Alanaktion** [comment]
I can't seem to reproduce this. What browser are you using and what theme do you have selected?

**Comment by volomike** [comment]
I tried my best to demonstrate this. I have it loaded on A2 Shared Hosting. My DSL connection runs around 2.1Mbps. http://screencast.com/t/scimDNzISfU   If you want to see it live, then email me at volo m i k e at g m ail  and I'll give you an exclusive login. To match Internet speeds, which I'm pretty certain are going to be way faster on your Internet connection than mine, you could play like 4 YouTube videos simultaneously while loading pages off my hosting plan.

**Comment by Alanaktion** [comment]
Ah, okay, I see what's going on. I've mostly used it on an internal server, so it was only being throttled by the internal network, which is Gigabit in my case. I'll try using Chrome's built-in bandwidth throttling in the developer tools and see if I can't get it better optimized for a slower connection.

**Comment by Alanaktion** [comment]
Okay, this should be fixed now.
