### ISSUE TITLE
New Record Creation Speedups

### ISSUE THREAD

**Issue by volomike** [Alanaktion/phproject#232]
I noticed when I create a new project or task (or perhaps it's anything from the New menu) that when I fill out the form and hit submit, it takes a few seconds. Is there any way to refactor this so that it speeds this up some more? I mean, when I was trying to enter 10 projects, I had to wait for this each and every time on my shared hosting account, although other things I run on my shared hosting account don't seem to have so much delay. It's not a huge problem, and it's definitely not a showstopper. Most people wouldn't notice it, but I'd like to point out things that could help you make this awesome application even better than it already is.

**Comment by Alanaktion** [comment]
It takes 65 milliseconds on my setup. Maybe you have a problem with your database connection or email configuration?

**Comment by BerChill** [comment]
I'm also on a shared hoster. For me it takes less than 1 second to create any project or task from the "new" menu with "send notifications" enabled. Virtually no delay when adding comments.
