### ISSUE TITLE
Opening Project or Task - Tab Delay

### ISSUE THREAD

**Issue by volomike** [Alanaktion/phproject#233]
I noticed that when I open a project or task, the tabs above the comments field have a little bit of a delay on loading as if they're trying to adjust their position. Is there any way to hide these until they finish loading, then reveal, or figure out what causes this and refactor it? This is an extremely minor issue, but one I notice, none the less.

**Comment by Alanaktion** [comment]
They're updating the count of items for each tab as they load. I'm not sure how I'd change that, and since the labels only shift a few pixels I feel like anything done to work around it would just make the UI less usable. For example if one of them didn't load quickly for some reason, then none of the tabs could be used until it finished.

**Comment by volomike** [comment]
Here's my video where I demonstrate this issue. http://screencast.com/t/scimDNzISfU  My suggestion is to add a cron job (or perhaps do a random run on every dashboard load, and use a session cookie to only run once per day) so that the counts are calculated and cached in a summary table rather than being calculated on each page load. And, if that's still not good enough, then use jQuery to hide the items until the last item is calculated, and then show the tabs. As for the hiding, we're probably only talking about 1 second, max, unless that summary table speeds that up a great deal.

**Comment by volomike** [comment]
I think there's a way to do this. If you put an ID on this in single.html:

`$($('.nav.nav-tabs')[1])`

(in other words, this is the second case of .nav.nav-tabs on the page, thus `[1]`)

Then, you can style it in the CSS and set default visibility to hidden. Then, in single.html where you load the dependencies in jQuery, after this line...

`$('#dependencies_badge').text(data.total);`

...then add this line:

`$($('.nav.nav-tabs')[1]).css('visibility','visible');`

So basically, when single.html loads, the default styling of that tab bar in particular is hidden, but displayed (so, not display:none, but visibility:hidden). Then, when you update the dependencies badge, set visibility:visible again.

What this does is eliminate the flashing on the page and makes it appear to load faster.

That can be step 1 and is an improvement in my opinion.

The second step can be that you can rework the AJAX call so that instead of it asking the controller to call the model to recalculate totals all over again (if that's what it's doing), it can simply ask the controller to get totals from a summary table that gets updated whenever it needs to get updated.
