### ISSUE TITLE
due issues notifications

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#235]
ENHANCEMENT

At the start of a new day, the user could be reminded of his/her issues that are due today or overdue via notification mail. Preferably, this feature can be toggled in the account settings so that the user can opt-out of this.

**Comment by Alanaktion** [comment]
This exists, but may not be documented. If you set up a cron job to run `php crons/due-alerts.php` daily, that will send an email to anyone with something due that day. Overdue issues currently aren't included, but I'll definitely add that, and I can add a user setting as well.

**Comment by Alanaktion** [comment]
Okay, I've added the overdue issues and the user setting. I'll leave this open until I add documentation as well.

**Comment by BerChill** [comment]
Awesome, thank you!

**Comment by BerChill** [comment]
Hi Alan,

I tried setting up a cron job but it outputs the following:
"Could not open input file: [MyBaseDirectory]/public_html/aufgaben/cron/due-alerts.php" ([MyBaseDirectory] replaced by me as an obfuscation)

The access rights are the same as with `checkmail2.php`. Trying to run this via `wget URLtoFile` won't work either as it returns that cron jobs have to be executed via CLI, which was to be expected.

**Comment by Alanaktion** [comment]
It's actually `crons/due_alerts.php` with a `_` instead of a `-`. I wrote it wrong in my comment.

**Comment by Alanaktion** [comment]
I've added [documentation](http://www.phproject.org/use.html#due-issue-alerts) for this feature now.

**Comment by BerChill** [comment]
Now, this is just embarassing on my side ... Made sure I copy and paste the path of my installation correctly but not checking the file name :)
