### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by n8225** [Alanaktion/phproject#257]
Demo site at http://demo.phproject.org/ returns error 502.  Has the demo been removed or moved somewhere else?

**Comment by Alanaktion** [comment]
I'm having a lot of issues with that server, for some reason the PHP service is crashing on it every few minutes. I may migrate the demo site to another server soon if I can't figure it out.

**Comment by Alanaktion** [comment]
The site is fairly stable now on a new server, but I may put it behind a login soon to avoid the spam issues I've been having.
