### ISSUE TITLE
Some Hotkeys don't work with Firefox or Chrome

### ISSUE THREAD

**Issue by Nebucatnetzer** [Alanaktion/phproject#261]
On Firefox and Chrome Alt+1, Alt+2 and Alt+3 already have a function (jumping to Tab 1-3)which makes it impossible to use the phproject hotkeys.

**Comment by Alanaktion** [comment]
For some reason these worked for me on at least one of those browsers when I first added them, but it looks like the browser defaults are taking priority now. I'll change the hotkeys to be less generic.

**Comment by Nebucatnetzer** [comment]
That would be greate :).
I can imagine that it might make it much quicker to use with the shortcuts.
Let me know if I can help with testing or so.
