### ISSUE TITLE
Input on Firefox Mobile is a bit wonky

### ISSUE THREAD

**Issue by Nebucatnetzer** [Alanaktion/phproject#262]
When you enter something in a text field and try to delete it and then continue writing the input goes completely haywire. I don't know if it happens on other mobile browsers as well. It looks a bit like spellchecker could be the problem but that's just a guess.

**Comment by Alanaktion** [comment]
Apparently the editor I'm using is very buggy on mobile. I hadn't tried it in a while. I was able to reproduce the issue on Chrome and Firefox on Android.
As a temporary solution, you can disable the editor in your account settings (My Profile > Settings), and I'll look into a solution for this issue. Most likely I'll be disabling the editor on mobile and looking into alternatives that better support it.

**Comment by Nebucatnetzer** [comment]
Thank you for the tip with editor. Worked well.
If you need someone for testing let me know.
