### ISSUE TITLE
New type of object & suggestion/request

### ISSUE THREAD

**Issue by Abraka** [Alanaktion/phproject#271]
Hello, firts thank you for nice and simple project.
I have question/request about additional features. Im looking into phproject features for last two days and would like to have a feature which create predefined template-form in scenario like this...Im creating new task when new employe arrive at our organisation and there are several task needed to be done by different departments like personalist, IT, security, bulding manager etc. So instead of creating like 15 subtask by hand, which is very hard to do, I would like to have a template-s which gave me ability to automatize this process, so I just simply pickup template new-employe and all predefined task to predefined set of groups and people will be created.
Another thing, I notice that search function cant find uploaded files, when I search for their names.

**Comment by Alanaktion** [comment]
For the user template, I would recommend making a user that you assign your starting tasks to. When a new user is created that needs those tasks, you can use the Browse menu to find your starting tasks, and use the Bulk Update to make a copy of the tasks and update the assigned user.

For search, I'm planning on rebuilding the entire search system to be more flexible. I've added a new issue for searching files, #276.

**Comment by Abraka** [comment]
Well, thats not flexible nor efficient solution. Imagine, that you get new employe for example, then you create task "New employe Adam Smith" and when creating this task, there should be a option "choose task template", then you choose "New employe" and thats it. Now, it will be automatically created set of tasks for different groups and users inside phproject. This scenario of automatic advance task creation process can be applied to anything and if you need often assing lot of repeated tasks, this would be a life saviour. This should be part of every project management app with tasks.

**Comment by Alanaktion** [comment]
That should already be possible with the current Copy functionality. You can create a task that includes child tasks assigned to different groups and users, and copying that task includes all of it's descendants.

**Comment by Abraka** [comment]
Thats true. But it would be nice to have this incorporated directly in dialog for creating tasks.
