### ISSUE TITLE
Security - Access by groups and users?

### ISSUE THREAD

**Issue by Abraka** [Alanaktion/phproject#279]
I didnt find where I can setup what project or task can user see and work with. If I have several departmens and each have of course different tasks I dont want let users from building management see task and  projects from IT department. How to do that?

**Comment by BerChill** [comment]
AFAIK, the current permission system supports editing restrictions only. Currently, all issues are visible to everyone who has access to the system. Maybe this could be added to the "Permission System" Milestone?

**Comment by Alanaktion** [comment]
Yes, currently there is no way to restrict access to issues. It's been a feature I've considered introducing for a few years, but we haven't seen the need for it in our use yet. See issue #45.

If you guys have any ideas on how you'd like to see this implemented, please add them as comments on #45, and I'll see what I can do 😄

@BerChill I'll definitely consider adding this to the permissions system milestone, but it could be a significant change to how the entire system functions now depending on how it's implemented so I may keep it separate.
