### ISSUE TITLE
Detailed user permissions

### ISSUE THREAD

**Issue by MatheusGrilo** [Alanaktion/phproject#28]
Some plans for Groupped Projects?

for example:
Admin can edit Everything in a project (Informations, Status)
Contribuitors can edit/modify/send something on project and mark bugs as fixed
Normal users can comment about some issue

**Comment by k2kirov** [comment]
Hey Alan, can i help you in developing grouped permissions, i am interested in such a feature.

**Comment by Alanaktion** [comment]
This is being worked on in #46, and is mostly working.
