### ISSUE TITLE
SQLSTATE[#4200] [1115] Unknown character set: 'utf8;' During install.

### ISSUE THREAD

**Issue by d5c4b3** [Alanaktion/phproject#287]
I am trying to get this set up on 000webhost. When I go to install.php and try installing I get SQLSTATE[#4200] [1115] Unknown character set: 'utf8;'. 

This is the server information I could get from phpmyadmin

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.1.18-MariaDB - MariaDB Server
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)
    Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 
    PHP version: 7.0.8

**Comment by Alanaktion** [comment]
I'm attempting to set up a copy myself on 000webhost, but I'm having trouble getting the files to upload without timing out. I'll let you know what I find when I can get the upload to complete successfully.

**Comment by d5c4b3** [comment]
I was using filezilla when I did. I had to change the timeout to 90 for it to upload them. It still took forever and it did occasionally timeout, but it was noticeably faster.

**Comment by Alanaktion** [comment]
This appears to be a bug on 000webhost's end, most likely implemented as a security precaution. You can work around the issue by changing the 6th-to-last line of `lib/db/sql.php` to remove the `.';'` part. This query seems to be what's causing the issue.
It is [working for me](https://phproject-test.000webhostapp.com/) after this change, but it's quite slow and the database server frequently disconnects unexpectedly, so I'd highly recommend paying for an actual webhost if possible :)

I haven't been able to reproduce this issue with any other webhost so far in my testing, on any PHP or MySQL version, and it's not a recently introduced change, so I'm going to consider it not a bug, but if you do see the same issue somewhere else, please let me know.
