### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by pieromobile** [Alanaktion/phproject#291]
After installation (OK) result is:

My URL: http://10.101.97.59:8087/login

**Not Found**
The requested URL /login was not found on this server.
Apache/2.4.25 (Debian) Server at 10.101.97.59 Port 8087

**Comment by Alanaktion** [comment]
You most likely need to enable `mod_rewrite` in your server's Apache configuration. This is likely as simple as running `sudo a2enmod rewrite` and restarting the Apache service (`sudo systemctl restart apache2` may work).

**Comment by pieromobile** [comment]
Same problem after execute.

<a href="http://it.tinypic.com?ref=11135fo" target="_blank"><img src="http://i64.tinypic.com/11135fo.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

URL
<a href="http://it.tinypic.com?ref=2luwbcz" target="_blank"><img src="http://i66.tinypic.com/2luwbcz.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Alanaktion** [comment]
Okay, you may need to change Apache's configuration to allow it to read the `.htaccess` file. You can do this by adding these lines to your `sites-enabled/...` file if you're using a VirtualHost, or your `apache2.conf` file if you're not.

```
<Directory /var/www/>
    AllowOverride All
</Directory>
```

If you're using a path other than `/var/www` for your web root, change the path in the `<Directory>` block to the one your files are in. After changing the file, restart Apache again and it should work.

**Comment by jennifer-sevenval** [comment]
Sorry for bumping an old thread, but I came across the same issue after installation of that package within my shared-hosting environment. Even placing an htaccess file with
 ``` 
RewriteEngine on
```
did not help... what is the error exactly and what do I have to do to solve it?

**Comment by Alanaktion** [comment]
@jennifer-sevenval you should be able to use it on Apache with the included `.htaccess` file. A shared hosting environment shouldn't need any extra setup if it's supported, as long as the `.htaccess` file from the project is present.
