### ISSUE TITLE
Unable to create a user

### ISSUE THREAD

**Issue by RickScalzo** [Alanaktion/phproject#302]
Hi,

I keep getting an error that says the user name exists when I trying to create a new one.

Any thoughts on what I did not set up correctly?

**Comment by Alanaktion** [comment]
Was the user deactivated? If so, you'll need to go to "Deactivated Users" and re-activate the existing user, rather than adding a new one.

**Comment by RickScalzo** [comment]
No. It was the first time I was adding a user on a clean install.

**Comment by Alanaktion** [comment]
This may have been caused by a bug that displayed the wrong message if a password was not entered. I've updated the messaging to be accurate. It's also possible to see this error if you try to create a group and a user with the same username.

**Comment by RickScalzo** [comment]
Do I need to do an update?

**Comment by Alanaktion** [comment]
An update will show the correct error message. I just released [version 1.5.1](https://github.com/Alanaktion/phproject/releases/tag/v1.5.1) which includes that fix.
