### ISSUE TITLE
Javascript error for italian translation

### ISSUE THREAD

**Issue by giosueDelgado** [Alanaktion/phproject#306]
When I use the italian translation the javascript give me a "SyntaxError". You can correct the error by editing the file it.ini and replacing the character ' with \'

**Comment by Alanaktion** [comment]
I'm unable to reproduce this error with the current code. Which page are you seeing the error on?

**Comment by giosueDelgado** [comment]
If you set the Italian language and go to one Project.
If you click on history you get the error.

I fixed it replacing on the file it.ini the character
`'` with `\'`

**Comment by Alanaktion** [comment]
Okay, we had a fix in place for that but it was not included in a release yet. Version [1.5.1](https://github.com/Alanaktion/phproject/releases/tag/v1.5.1) includes a fix for this issue.
