### ISSUE TITLE
Error while setting database

### ISSUE THREAD

**Issue by russanvan** [Alanaktion/phproject#310]
SQL query: Documentation

CREATE VIEW `user_group_user` AS (
SELECT `g`.`id` AS `id` , `g`.`group_id` AS `group_id` , `g`.`user_id` AS `user_id` , `u`.`username` AS `user_username` , `u`.`email` AS `user_email` , `u`.`name` AS `user_name` , `u`.`role` AS `user_role` , `u`.`task_color` AS `user_task_color` , `u`.`deleted_date` AS `deleted_date` , `g`.`manager` AS `manager`
FROM (
`user_group` `g`
JOIN `user` `u` ON ( (
`g`.`user_id` = `u`.`id`
) )
)
);

MySQL said: Documentation
#1142 - CREATE VIEW command denied to user 'bx_xxxxxx'@'xxx.xxx.0.6' for table 'user_group_user'

**Comment by Alanaktion** [comment]
This happens if your database user is not allowed to create views. You will need to ask your hosting provider for access to create views in MySQL.

**Comment by russanvan** [comment]
Thank you! I have just solved this issue.

**Comment by russanvan** [comment]
However, after successfully setting up database, there was an error in mydomain.com/login

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Alanaktion** [comment]
Are you able to get the messages from the server error log? It could be a lot of different things with just an internal server error.

**Comment by russanvan** [comment]
I don't know how to fix it. I am not a developer, so I can't detect the error. I have installed phproject on 1&1 server. Can you give me some tips?

**Comment by Alanaktion** [comment]
Most shared hosting providers allow you to create a custom PHP configuration. [1&1 appears to support this](https://help.1and1.com/hosting-c37630/scripts-and-programming-languages-c85099/php-c37728/enable-error-logs-a792503.html). Try creating a `php.ini` file in the same folder as the phproject code, with these contents:
```ini
error_reporting = E_ALL | E_STRICT
log_errors = On
display_errors = On
```

This should make PHP display more error information that could be helpful in fixing the issue.

**Comment by russanvan** [comment]
Although I installed php.ini with these contents, there are no changes. The login page still informs 500 internal error. Could I know where to find the error information?

**Comment by Alanaktion** [comment]
It's different for every hosting provider, so you'll need to go through 1&1 for more info than that.
