### ISSUE TITLE
Remove login functionality

### ISSUE THREAD

**Issue by shahzadthathal** [Alanaktion/phproject#313]
Hi,

Can you please let me know how can I remove whole login functionality?

Actually, I don't need the login functionality because I'm using my own session but every time it redirects me to the login page.

Thanks

**Comment by Alanaktion** [comment]
There are a few different approaches you could take with this. One would be to have your custom sessions insert a row into the `session` database table and set the `phproj_token` cookie for the user so Phproject sees them as authenticated. Another option would be to implement a custom login like the [googleauth plugin](https://github.com/phproject-plugins/googleauth) does, adding an additional route that can generate a session for the user, and optionally also a script in the standard login that triggers that route.

**Comment by Alanaktion** [comment]
Eventually we'll support unauthenticated access without any modifications, but that's not quite finished. It was being worked on in the `guest-access` branch.

**Comment by shahzadthathal** [comment]
Thanks I will try.
