### ISSUE TITLE
Taskboard not showing in Overview

### ISSUE THREAD

**Issue by sebomoto** [Alanaktion/phproject#317]
I installed version v1.5.1. Everything seems to work fine, but i don't see the taskboard.

There is only the button "Manage Widgets".

If i enter the URL /taskboard, i get a 404 page.

First, i had updated an older version.
In my second attempt i installed from scratch, in a new folder and with a new database.
![grafik](https://cloud.githubusercontent.com/assets/5748177/25917526/abff6da0-35c8-11e7-8c1f-3ab41d0fe469.png)

**Comment by Alanaktion** [comment]
The taskboard shows projects and tasks in a sprint, so the button will only show if there's a sprint for the current date. If you want to use it without sprints, you could try creating a sprint with a far-future end date so it's always active.

**Comment by sebomoto** [comment]
Thanks for the quick response! Sorry as this was not a bug but a misunderstanding of how the feature works.

I have now created a sprint which starts today and ends in the far-future as suggested by you. When adding projects to the sprint, i can access them via the taskboard.

Are there plans for expanding the documentation? If yes, let me know if there is something i could help with. 

Best regards,

Sebastian
