### ISSUE TITLE
last inserted id

### ISSUE THREAD

**Issue by shahzadthathal** [Alanaktion/phproject#319]
Hi,

How can I get last inserted id?

Initializing database connection in index.php

```
$f3->set("db.instance", new DB\SQL(
	"mysql:host=" . $f3->get("db.host") . ";port=" . $f3->get("db.port") . ";dbname=" . $f3->get("db.name"),
	$f3->get("db.user"),
	$f3->get("db.pass")
));
```

Here is my code in controller:

```
$sql = "INSERT into table ...."
$res = $f3->get('db.instance')->exec($sql);
print_r($res); // always display me 1

echo $res->id; //Trying to get property of non-object
```

**Comment by Alanaktion** [comment]
Running `exec()` on an `INSERT` query should return an `int`, so you should just be able to use `$res`. See the [F3 documentation](https://fatfreeframework.com/3.6/sql#exec) for usage details.
