### ISSUE TITLE
Not working with MySQL server 8.0

### ISSUE THREAD

**Issue by sergyu91ma** [Alanaktion/phproject#328]
Please update queries from project to work with MySQL server 8.0.

**Comment by Alanaktion** [comment]
Since MySQL 8.0 does not have a general availability release yet, I'm not considering this a bug yet, but I'll look into it.

**Comment by sergyu91ma** [comment]
The most common error is the word --role-- which is a reserved keyword in MySQL 8.0 and needs to be replaced with `role` in queries. I did this locally on my server.
