### ISSUE TITLE
PDOStatement: Access denied; you need (at least one of) the SUPER privilege(s) for this operation

### ISSUE THREAD

**Issue by webunraveling** [Alanaktion/phproject#329]
#I originally installed using a ZIP file and figured I would upgrade today. I cloned the repo instead so it would be easier to update in the future. I copied my `config.ini` to the repo directory, then moved my repo directory to where my installation was located. My `config.ini` appears to have been replaced with `config.php`

I did this while logged in as admin. I refreshed the page and saw a message that the DB was updated. When I try to navigate anywhere in phproject I get the following error. I'm still looking but haven't been able figure out what the problem is. 

    PDOStatement: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
    [project/app/helper/security.php:163] DB\SQL->exec()
    [project/index.php:88] Helper\Security->updateDatabase()

**Comment by Alanaktion** [comment]
You can try checking the `version` number in the `config` table to see what the last successful update was:

```sql
SELECT `value` FROM `config` WHERE `attribute` = 'version';
```

Whatever file comes after that value in the `db/` directory is where it is failing. Most likely it is trying to update a view or something that was created using a different database user originally.

**Comment by webunraveling** [comment]
Thanks for the reply. You're probably on to something. I tried to do a fresh install with a new database. However, I did have to run `composer update` for `install.php` to load. I don't know if that helps narrow things down at all.

 Here is the output of the query: `16.11.29.1`. `16.11.29.1.sql` does not exist in my `db/` directory.
