### ISSUE TITLE
Installation failure issue???

### ISSUE THREAD

**Issue by tyncup** [Alanaktion/phproject#335]
I have attempted installation several times always getting the same error 

Internal Server Error
PDOStatement: InnoDB is in read only mode.

I have checked write permissions on the folders and all seem to be writeable
I have debugged down to the failing statement:

$db->exec(explode(";", $install_db));

Target environment is php 7.0.22 and mysql 5.6.35 - Must be something simple????
[my_sql_error.log](https://github.com/Alanaktion/phproject/files/1485798/my_sql_error.log)

**Comment by Alanaktion** [comment]
It looks like your MAMP MySQL has the `innodb_force_recovery` variable set, which is used to repair corrupted database files from a previous crash. It won't let you make changes to any InnoDB tables until that value is changed back to `0`, so you may need to edit your MySQL conf file and remove the recovery line. This is an issue with the InnoDB configuration or file corruption, not specific to Phproject.
