### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by tyncup** [Alanaktion/phproject#337]
after installation I always get a "404 Resource Not Found" on /admin.
My hosting provide indicates that mod_rewrite is enabled and AllowOverride All is set
Suggestions

**Comment by Alanaktion** [comment]
Do you only get the 404 error on `/admin` or on other URLs too? They should all work the same if those options are set right.

**Comment by tyncup** [comment]
Problem resolved via correct rewrite

**Comment by PiXBalance** [comment]
@tyncup how does your htaccess look like. I have the same issue. All URLs are working but the admin URL.
