### ISSUE TITLE
Email replies are not being decoded (?) and put out a long string of encoded text.

### ISSUE THREAD

**Issue by webunraveling** [Alanaktion/phproject#338]
Early on while setting up email functionality, I had this happened but was unsure why. After experimenting, with different settings and using phpmailer.php (instead of phpmailer2.php) in cron things worked fine. But today I saw it is not working again. It looks like base64 but when I copy and paste it, it appears to be malformed. I wish I could explain it better so here is a screenshot...

![screenshot of the comment in phproject](https://user-images.githubusercontent.com/10575666/34267257-d178d2ae-e641-11e7-9639-320f36b73e60.jpg)

**Comment by Alanaktion** [comment]
This seems similar to an issue I've seen with emails that had attachments. Sometimes the decoding doesn't work correctly since it finds an encoded attachment instead of the main message body, and puts that text as the comment instead. The `phpmailer2.php` script is *supposed* to properly detect those, but I could definitely see it having issues with certain email formats.

**Comment by webunraveling** [comment]
In case this makes a difference... right now, this is the cron that runs every few minutes: `php-cli /home/username/public_html/subDomains/project/cron/checkmail.php`

Probably on an unrelated note... `phpmailer2.php` produces an `error_log` file saying:

    [28-Dec-2017 19:03:24 UTC] Invalid argument supplied for foreach()

I assume this occurs when there are no new messages in the email inbox. That is the reason I am using `phpmailer.php`.

**Comment by Alanaktion** [comment]
I've not seen any errors from my servers running the `checkmail2.php` cron, but I've added some additional checks in the 1.7 release. The `checkmail.php` script doesn't support email with attachments and uncommon encodings and will be removed at some point, but the new script should work fine now.
