### ISSUE TITLE
Bug in the live demo

### ISSUE THREAD

**Issue by masterT** [Alanaktion/phproject#339]
I get a `500` status code when visiting the live demo https://demo.phproject.org/.

```html
<div class="alert alert-danger" id="error-msg">
    <p class="lead"><strong>500</strong> Internal Server Error</p>
    <p>session_set_cookie_params(): CookieLifetime cannot be negative</p>
        </div>
```

**Comment by Alanaktion** [comment]
Ah, I forgot about that one. There's an issue with PHP 7.2 and a bug in the current master code. I've temporarily moved the demo site to the `v1.7-dev` branch which fixes the issue. That branch will be released as version 1.7 very soon so it's not too far from the current code 😉
