### ISSUE TITLE
cookie issue at installation time , server 500 error

### ISSUE THREAD

**Issue by jseutens** [Alanaktion/phproject#344]
after filling in the needed data in install.php i got following message on the website
Internal Server Error
session_set_cookie_params(): CookieLifetime cannot be negative

the error log is
[Wed Feb 07 21:55:31.246993 2018] [proxy_fcgi:error] [pid 26381:tid 140430878865152] [client IP_REMOVED:62382] AH01071: Got error 'PHP message: session_set_cookie_params(): CookieLifetime cannot be negative\nPHP message: [app/model/config.php:102] Base->set()\nPHP message: [install.php:78] Model\\Config::setVal()\n', referer: https://URL_REMOVED/install.php

Line 102 is in this function (bold text)

    public static function setVal($key, $value)
    {
        $f3 = \Base::instance();
        **$f3->set($key, $value);**
        $item = new static();
        $item->load(array('attribute = ?', $key));
        $item->attribute = $key;
        $item->value = $value;
        $item->save();
        return $item;
    }

**Comment by Alanaktion** [comment]
Thanks for reporting this. It's an issue I've been aware of for a little while that only affects recent PHP releases, but definitely needs to be fixed. I've got a plan for how to fix it, and should have something released soon. Right now there's no easy way to bypass it other than to modify the install.php and your config table, which I can explain in detail if you want to know how to install it before I have the fix ready.

**Comment by jseutens** [comment]
I can switch to php 5.6 , 7.0 or 7.1 , currently using 7.2
Will let you know with one is working , but if you have a fix , please post i i will implement and test it on 7.2

**Comment by jseutens** [comment]
7.1 is working :-) 7.2 not , didn't test the older ones.
Happy for the moment :-)

**Comment by Alanaktion** [comment]
Okay, this should be fixed in [release 1.7.2](https://github.com/Alanaktion/phproject/releases/tag/v1.7.2). It was technically broken before PHP 7.2, but earlier PHP versions ignored the error. This new release should work on all PHP versions.
