### ISSUE TITLE
duplicate security headers

### ISSUE THREAD

**Issue by jseutens** [Alanaktion/phproject#346]
There was a duplicate X-Content-Type-Options header.
There was a duplicate X-Frame-Options header.
There was a duplicate X-XSS-Protection header.

These headers are already implemented server side , the project website is the only one where i get the duplicate messages , Is there a way to disable these 3 security headers in your code ?
The values are the same on server side as on website side.

X-Frame-Options  : SAMEORIGIN
X-XSS-Protection : 1; mode=block
X-Content-Type-Options : nosniff

**Comment by Alanaktion** [comment]
There is not currently a way to disable these headers. I would recommend configuring your server to replace the headers instead of adding additional ones.
