### ISSUE TITLE
update from 1.3.1 to 1.7.3

### ISSUE THREAD

**Issue by starsnet** [Alanaktion/phproject#347]
hi all

can I update from 1.3.1 to 1.7.3 immediately?
or update gradually: 1.3.1 -> 1.4.0 -> ... 1.7.2->1.7.3

**Comment by Alanaktion** [comment]
It should be safe to do one upgrade, but I would recommend backing up your current site before starting just in case.

**Comment by starsnet** [comment]
thank you
