### ISSUE TITLE
direct routing to edit issue has problem with empty(@issue.priority_id)

### ISSUE THREAD

**Issue by Citydampf** [Alanaktion/phproject#355]
when you edit an issue directly (GET /issues/edit/@id = Controller\Issues->edit)  you will loose the priority-level cause there is an empty issue.priority_id. -> selected default

**Comment by Alanaktion** [comment]
Good catch! I'm not actually sure why that doesn't break the inline edit form, but it should be fixed on the master branch now. There should be a new release out that includes this fix within a couple weeks.

**Comment by Citydampf** [comment]
the inline form comes from single function which calls $issue = new \Model\Issue\Detail;
and edit function calls only  $issue = new \Model\Issue;
thats why priority_id array is missing.
