### ISSUE TITLE
safe-Mode

### ISSUE THREAD

**Issue by ChrMue** [Alanaktion/phproject#358]
Hallo,
on start of phproject I get an error
Fatal error: Directive 'safe_mode_protected_env_vars' is no longer available in PHP 5.4 or newer

After 2 reloads it works fine.
The webspace is running witth PHP 7.1 and therefore safmode is off (answer of the hoster)
Do you check the safe-mode or use safe_mode commands?

KR
ChrMue

**Comment by Alanaktion** [comment]
Nothing is intentionally done with safe mode that I know of, but I can look into this.

**Comment by Alanaktion** [comment]
This directive (`safe_mode_protected_env_vars`) isn't accessed anywhere in Phproject or any of its dependencies, and is running fine in several other PHP 7.1 environments, so this is likely an issue with your server configuration in some way. I would make sure that your `php.ini` file doesn't contain anything related to `safe_mode`, but I don't think this error is related to Phproject.
