### ISSUE TITLE
error 500 when sign-in with a new account

### ISSUE THREAD

**Issue by Rayman223** [Alanaktion/phproject#363]
Hi !
When I try to sign-in (check the screenshot), I have an 500 error :

> 500 Internal Server Error
> PDOStatement: Data too long for column 'task_color' at row 1

I'm using wamp server 3 in local.
![phproject_1](https://user-images.githubusercontent.com/29522521/45888214-ce280d00-bdbd-11e8-8eb6-bb1fadfe411e.png)

**Comment by Alanaktion** [comment]
I've added a bug fix for this, it should go out with the next release.
