### ISSUE TITLE
Error message displayed when adding a comment : but comment is posted

### ISSUE THREAD

**Issue by bestkiller92** [Alanaktion/phproject#366]
https://github.com/Alanaktion/phproject/blob/92176d1e51086c10eceb34fedf80b29dadcedf98/app/view/issues/single.html#L401

I've found a quite simple solution :
"$.post($this.attr('action'), serialize($this), function(data) {"

This solve the issue, and comment are updated immediatly in the page.

**Comment by bestkiller92** [comment]
The issue is not happening on Safari and Internet explorer.

**Comment by Alanaktion** [comment]
I haven't been able to reproduce this in any environment but if there is more detail I can implement a fix.
