### ISSUE TITLE
404 error on shared hosting

### ISSUE THREAD

**Issue by optico** [Alanaktion/phproject#369]
After installing I get a 404 Not Found error for /login and /admin so its not working. What do I wrong? I'm on a shared hosting. Do I have to make a .htaccess file? And if yes: What needs to be in it then?

**Comment by Alanaktion** [comment]
If your shared hosting uses Apache, there is already a `.htaccess` file included that should work fine, so make sure that file is on the server. If it doesn't work with the file included, you'll need to check with your hosting provider to make sure `mod_rewrite` is enabled.
