### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by optico** [Alanaktion/phproject#371]
I get an blank page when I go to the install page. So I can't install it. Plz help thnx

**Comment by Alanaktion** [comment]
Have you checked for any errors in your server error log? Most likely, you are missing one of the required PHP extensions.

**Comment by Citydampf** [comment]
also config.php under app/model is missing in download zip file (last version).

**Comment by Alanaktion** [comment]
Not sure if that was the cause of this issue, but @Citydampf that should be fixed now.
