### ISSUE TITLE
Se produjo un error con peticiónes relacionados.

### ISSUE THREAD

**Issue by oscararenas86** [Alanaktion/phproject#375]
al intentar abrir las tareas secundarias se produce el error "Se produjo un error con peticiónes relacionados".

Al intentar abrir observadores se produce el error  "Se produjo un error con los observadores."

Al intentar abrir dependencias se produce el error "Se produjo un error con los dependencias."

Se esta usando windows 10 con xampp con php 7.3.1

![error phproject](https://user-images.githubusercontent.com/54293958/63367085-af6d2600-c340-11e9-9f49-eb8f9c808b87.png)

**Comment by Alanaktion** [comment]
¿Tienes tu registro de errores de PHP? Es útil para solucionar este problema. Probablemente en `C:\xampp\php\logs\`.

**Comment by oscararenas86** [comment]
Muchas gracias por la pronta respuesta Alanaktion, ya no logre recuperar el log, pero ya funciono correctamente, te explico, estaba utilizando windows 10 con xampp con **php 7.3.1(fallando)**, cambie a windows 10 con xampp con **php 7.3.2 (funcionando)** y se soluciono el problema.

**Comment by Alanaktion** [comment]
Alegra que esté funcionando!
