### ISSUE TITLE
Invalid image URI on local avatars

### ISSUE THREAD

**Issue by Backpackstudio** [Alanaktion/phproject#379]
On case of local avatars an invalid image url is provided. Message contains relative url, but should have full url of avatar image.

**Comment by Alanaktion** [comment]
Is this specific to the avatar displaying in emails or something like that? It should work correctly as a relative URL in a browser.

**Comment by Backpackstudio** [comment]
Sry.  I didn’t clarified well enough, that topic is related to email messages. Web based GUI doesn’t have this issue. It occurs on emails, but weirdly on some messages avatar icons are  fine, and then is relative, not full path used,

**Comment by Backpackstudio** [comment]
Local avatar != Grvatar

**Comment by Alanaktion** [comment]
This is an issue with the installer not setting the `site.url` configuration option. I'm fixing it in the next release, but your current site will need to have a manual change made. In the config.php file, add a line like this with your site URL:

```
'site.url' => 'http://projects.example.com/',
```

The emails themselves will already include the correct site name as long as this value is set.
