### ISSUE TITLE
Auto-size comment textarea

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#381]
I often find it annoying to type more than 1-2 lines in the comment field, since it only renders ~2 lines while typing. It makes sense to me to make it auto-expand as you type, up to a reasonable maximum or maybe even indefinitely, then return to its original size after submitting. The initial size should probably be a bit bigger too, though maybe just on focus.

Relatedly, GitHub's issues start with 8 lines of space when creating a new issue, and 4 lines when commenting, but both auto-expand to fit contents beyond that point.

**Comment by Backpackstudio** [comment]
I agree!
