### ISSUE TITLE
Error: wrapper is disabled in the server configuration by allow_url_fopen=0

### ISSUE THREAD

**Issue by Backpackstudio** [Alanaktion/phproject#387]
I get strange error:

```
file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
[app/controller/admin.php:108] file_get_contents()
[index.php:147] Base->run()
```

Why system is trying to load external files?

```
        $context = stream_context_create($options);
        try {
            $result = file_get_contents($endpoint, false, $context);
        } catch (\Exception $e) {
            $this->_printJson(['error' => 1]);
            return;
        }
```

**Comment by Alanaktion** [comment]
You didn't give much of a context for this error, but it is most likely the update checker, that also includes some basic anonymous statistics. It likely makes sense to add a configuration option to disable this, but right now it is hard-coded to make this request from the admin panel, though it shouldn't affect any normal functionality when it breaks like this.

**Comment by Alanaktion** [comment]
The [included statics](https://github.com/Alanaktion/phproject/blob/15220615a3e0c3c676bd5c4669e151edc27e484d/app/controller/admin.php#L74) are very basic and not uniquely identifiable, they're just helpful for me to know the general size of the companies using it, and whether people actually install updates.

It reports these values:
- Installed Phproject version
- Unique random number (used to avoid duplicate submissions inflating total install count)
- Number of users
- Number of groups
- Average number of users per group
- Number of issues
- Number of sprints
- Database upgrade version (to diagnose if upgrades are not applying correctly with Phproject releases)

If the connection for this fails, as it does with `allow_url_fopen=0`, the application still fully functions, it just doesn't notify you in the admin panel when an update is available.

**Comment by Alanaktion** [comment]
You can disable the statistics reporting by setting the `site.disable_stats` configuration option to `1` in your `config` table, though the update check will still be attempted, so you will still see the error.
