### ISSUE TITLE
Undefined class constant

### ISSUE THREAD

**Issue by emike09** [Alanaktion/phproject#391]
When attempting to browse to our PHProject installation, I'm getting the following error message:

```
500 Internal Server Error

Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' [/var/www/projects.utahca.org/vendor/bcosca/fatfree-core/db/sql.php:517]
```
This has been happening for a few months, however sometimes I'm able to log in just fine without any issue, so the problem is intermittent. 

Ubuntu 18.04.5
PHProject Version: 1.7.9
PHP Version: 7.4.10
MySQL version: 14.14 Distrib 5.7.31 for Linux

Any tips?

**Comment by Alanaktion** [comment]
You likely need to enable the `pdo_mysql` extension in your `php.ini` configuration.

https://stackoverflow.com/q/2424343/873843

**Comment by emike09** [comment]
That did it! It was related to upgrading to PHP 7.4 and not updating php.ini with the required extensions.
