### ISSUE TITLE
email is up?

### ISSUE THREAD

**Issue by amammad** [Alanaktion/phproject#398]
hey dear phproject team.
is following email still works ? 
`alan@phpizza.com`

**Comment by Alanaktion** [comment]
Yes, I don't check it very often. I've seen your messages and will respond.

**Comment by amammad** [comment]
hey man, i want to tell just one thing.
huntr team will be accept csrf vuln that is universal in future within one report you can ask them and also they will collect all csrf to one report with multiple permalink that matches to every vulnerable endpoint.
at this time you can accept all csrfs and i very appreciated you to validate all of them because huntr team also in future want to give more reputation and bounty to universal vulnerabilities and this is not dair for me because report earlier.
again thanks for accepting my report Although you aware of them before.
excuse me for taking your valuable time.

**Comment by amammad** [comment]
hello sir.
can you give me any feedback?

**Comment by amammad** [comment]
Dear Alanaktion can i ask you to validate my other CSRF reports on huntr.dev? this is right that with one fix all of mine reports will be solved but in my side as a penetration tester there is more than one vulnerability.

Best regards,Amammad.
