### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [Alanaktion/phproject#401]
Hi few optential security vulnerability has been disclosed to huntr against your repo
plz validate them 
https://huntr.dev/bounties/1183df1a-5243-42f9-a263-267b92444b03/
https://huntr.dev/bounties/66a373c0-f89b-4a49-a996-7e1968cf72b8/
https://huntr.dev/bounties/a465d272-35fc-4f9c-99f3-b89790c5ad1c/

**Comment by ranjit-git** [comment]
are you looking into this?

**Comment by bestkiller92** [comment]
Doesn't look like :/ we cannot read the report anyway

**Comment by ranjit-git** [comment]
> Doesn't look like :/ we cannot read the report anyway

@bestkiller92 if you are repo maintainer then only you can read the report by signup

**Comment by Alanaktion** [comment]
These issues are fixed in v1.7.12
