### ISSUE TITLE
Bug found on issues : XSRF token reading

### ISSUE THREAD

**Issue by bestkiller92** [Alanaktion/phproject#405]
phproject/app/controller/issues.php 
public function reopen($f3, $params)
    {
        $this->validateCsrf(); >> issue is comming from this line : 

phproject/app/helper/security.php --> 
$cookieToken = $f3->get('COOKIE.XSRF-TOKEN');
        $requestToken = $f3->get('POST.csrf-token');

When clicking on "reopen" there is no "POST" data, therefore the error 400 is triggered
I didn't find any solution for now.
Workaround : comment the $this->validateCsrf(); line

**Comment by Alanaktion** [comment]
This is fixed in v1.7.12
