### ISSUE TITLE
Use  Linux  install  phproject  use  git   ,but   login  Error

### ISSUE THREAD

**Issue by ago1414** [Alanaktion/phproject#409]
I   see  **https://www.phproject.org/use.html**
--------------------------------------------------------------------
procedure  below

sudo  apt update
sudo  apt install  php  php-cli  composer  git   mariadb-server  php-mysql  php-gd apache2

cd   /var/www/html
sudo git clone https://github.com/Alanaktion/phproject.git
cd phproject
composer install
sudo  apt install   php-xml
composer install

sudo  chmod 777   /var/www/html/phproject
sudo  chown -R  www-data:www-data  /var/www/html/phproject 

cd phproject
composer install
---------------------------------------------------

Database  procedure
-------------------------------
sudo mysql -u root
CREATE DATABASE jitamin ;
CREATE USER 'jitamin'@'localhost' IDENTIFIED BY 'jitamin';
GRANT ALL PRIVILEGES ON jitamin.* TO  'jitamin'@'localhost';
FLUSH  PRIVILEGES;
\q
------------------------------------

Final  use   web  browser  to   install   phproject
192.168.XX.XX/phproject

**The  message  is   install  OK**
but  

http://192.168.1.201/phproject/login
or
http://192.168.1.201/phproject/

Browser  SHOW:
------------------------------------------------------
**Not Found**
The requested URL was not found on this server.
-------------------------------------------------------------
Apache/2.4.41 (Ubuntu) Server at 192.168.1.201 Port 80
-------------------------------------------------------------------

Can  Help  me to  resolve the problem 

Thanks

**Comment by Alanaktion** [comment]
See #369, #291, #117, or #22

**Comment by ago1414** [comment]
Thanks  I  resolve  it   ,  use  mod_write  

sudo  a2enmod  rewrite
sudo  vi  /etc/apache2/apache2.conf  
<Directory /var/www/html/phproject/>
        Options Indexes FollowSymLinks
        AllowOverride all
        Require all granted
</Directory>


sudo systemctl restart apache2
