### ISSUE TITLE
question about function allowAccess

### ISSUE THREAD

**Issue by Citydampf** [Alanaktion/phproject#413]
Hello Alan,
the behavor of this function is: when i assigne a ticket to another user, i cant see  it anymore when security.restrict_access is ON;
i am missing $this->author_id = $user->id in the IF
but it is philosophy.
https://github.com/Alanaktion/phproject/blob/f39a64025ceddbd2ebabcdc16b92aee5b8aaf7db/app/model/issue.php#L620

**Comment by Alanaktion** [comment]
I agree, the author should have access to view an issue they created when `security.restrict_access` is on. I'll update that.
