### ISSUE TITLE
Add delay to prevent accidental comment spamming

### ISSUE THREAD

**Issue by emike09** [Alanaktion/phproject#51]
It's easy to accidentally double click the save comment button, or to click, not see any progress, and click again to make sure that the button was clicked, only to see two comments post. 

Can we add a function that either delays how quickly users can save a comment in a particular thread, or that looks at the previous comment, and if it's the same, doesn't post the new one?

**Comment by Alanaktion** [comment]
Fixed for good in 4ab61c9.
