### ISSUE TITLE
Install SQL Troubles

### ISSUE THREAD

**Issue by jgill88** [Alanaktion/phproject#55]
I cloned the repo onto a server and had to change two things to get the install to go through:

Line 268 db/database.sql typeo `start_sate`, should be from what I can tell `start_date`. Looks like it was introduced in this commit: 
be09d9d9d8e21faf4351607543163f063d34aa90

And, the status field in the issue table is listed as signed but the primary key is unsigned in the issue_status, leading to errno 150. Looks like this was introduced in this commit: 50317dcc4f80628fa45883c4a05abb324f957c42

Making these changes, it installed correctly and seems to be working.

Thanks for the good work!
Josh

**Comment by Alanaktion** [comment]
Thanks for catching these, I figured we'd have some issues after I'd added the new foreign key constraints, although I thought I'd caught them all.
