### ISSUE TITLE
Feature: #hashtag

### ISSUE THREAD

**Issue by alexander-gess** [Alanaktion/phproject#64]
Sometimes need to found/group some similar task / projects, for example: #hardware #software. - it may be very usefull if lead many projects / task and sure it may usefull for make reports.

**Comment by Alanaktion** [comment]
This is an awesome idea, and something I've been thinking through for a while. I'll work on implementing it today.

**Comment by Alanaktion** [comment]
Okay, it's in. You can add #hashtags to descriptions and they'll become links and be saved in the `issue_tag` table. There's also a tag cloud at /tag/. I'll work on adding translations for the captions used.

**Comment by alexander-gess** [comment]
Thank you for feedback!!!
