### ISSUE TITLE
idea: change the "administration" on the metaphor icon

### ISSUE THREAD

**Issue by alexander-gess** [Alanaktion/phproject#74]
this is example of atlassian 
![2015-02-20 21 52 38](https://cloud.githubusercontent.com/assets/7859896/6305151/e6a7bfcc-b94a-11e4-98ce-fb9f510bf1d8.png)

we may change on "gear" of another one "administration" button...

**Comment by Alanaktion** [comment]
Ooh I like that idea. I'll make the change now.
