### ISSUE TITLE
Getiing htaccess: RewriteEngine not allowed error in Apache log.

### ISSUE THREAD

**Issue by shubham2809** [Alanaktion/phproject#78]
I tried to install in local server. But i am getting htaccess: RewriteEngine not allowed issue everytime i try to access it.

P.S: I enabled mod_rewrite.so and changed AllowOverride None to   AllowOverride All.

Could you please help.

**Comment by Alanaktion** [comment]
Make sure your `AllowOverride All` is in the right `<Directory>` block. It will only work properly when Phproject is within the folder specified in the `<Directory>` line (or one of its sub-folders).
This link may be helpful: http://stackoverflow.com/a/6997740
