### ISSUE TITLE
How can i install phproject.org project on xampp/wampp

### ISSUE THREAD

**Issue by shubham2809** [Alanaktion/phproject#79]
I am trying to install www.phproject.org project on local server. But, all possible attempts has failed.

I am aware that it require mod_rewrite to be enable. After searching on this issue i was able to resolve this on wampp. But not on xampp.

also, as you have mentioned in previous i have made changes to "AllowOverride All"

In wampp. it got stuck at install.php and nothing is displayed.

is there any procedure i can follow to successfully install at localserver.

Really appreciate any help provided.

**Comment by shubham2809** [comment]
I have made following changes in httpd.conf file

`<Directory "C:/wamp/www/phpproject">
      AllowOverride all
     Order Allow,Deny
     Allow from all </Directory>`

**Comment by dakrisis** [comment]
Is the subdirectory 'phpproject' correct? The official name is phproject (without the third 'p') which might be the actual directory where the files are residing. Also, make sure that AllowOverride all / Order allow/deny / Allow from all are all on a separate line within the <Directory> directive.
