### ISSUE TITLE
User deactivation

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#87]
Change user delete to deactivate, and add a restore feature/button.

**Comment by Alanaktion** [comment]
Delete has been changed to Deactivate, I will add a restoration feature later.

**Comment by ikkez** [comment]
There is no way to view a deleted/deactivated user. I was not able to change my email address, because it was already taken by a user which I recently deleted.

**Comment by Alanaktion** [comment]
@ikkez, yes, it currently has to be done from the database. I'll be adding an interface for viewing deactivated users soon.

**Comment by ikkez** [comment]
yes i did that in the database now. btw: phproject is a very nice management app so far. good work, I really like it. :+1:
