### ISSUE TITLE
missing base path in "add user to group" ajax route

### ISSUE THREAD

**Issue by ikkez** [Alanaktion/phproject#90]
Hi alan.
I wanted to add a user to a group, but the ajax request failed. 

![screenshot 2015-06-09 15 16 31](https://cloud.githubusercontent.com/assets/1177647/8058612/e206616a-0eba-11e5-8782-ac427e08182e.png)

My phproject app lives in a subfolder. 
The route should be `http://testwerk.int/phproject/admin/groups/ajax` here.

**Comment by Alanaktion** [comment]
It should work correctly now.

**Comment by ikkez** [comment]
works. thanks :+1:
