### ISSUE TITLE
removing a project from a sprint doesn't effect its tasks

### ISSUE THREAD

**Issue by ikkez** [Alanaktion/phproject#94]
When I remove a project from a sprint (drag it from sprint and drop it back to the backlog) it only updates the single project issue, but all it's tasks/sub-tasks are still set to the sprint, which causes the whole project and its tasks still be visible in the taskboard.
In addition: There is no mass update function to set none sprint for selected tasks, so I'm left with editing each single task manually and remove the sprint.

**Comment by Alanaktion** [comment]
I'm still working out how this should work. Currently, the best option is to use the Browse page, putting the project ID in the "Parent ID" filter, and using the Bulk Update at the bottom of the page.

**Comment by ikkez** [comment]
well the drag and drop feature is very nice so far. It took me a while to realize that only the very last child projects are displayed in the backlog. Projects which contain a sub-project were not shown there. It's okay like that and I guess it's reasonable (if that behaviour is intended!?), but a little info message in the docs about that would be nice.

**Comment by Alanaktion** [comment]
I've added a "No Sprint" option to the bulk update.

**Comment by Alanaktion** [comment]
Our usage of this functionality internally has worked out well the way it is now, so that work on tasks in the project's original sprint isn't moved out, so I'm going to close this. The bulk update should provide the functionality needed for most use cases.
